/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import Bean.HoKhauBean;
import controllers.ThuTienPanelController;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import views.ThuTienFrame.LichSuJFrame;
import views.ThuTienFrame.QuanLyKhoanThuJFrame;
import views.ThuTienFrame.ThuTienJFrame;

/**
 *
 * @author ADMIN
 */
public class ThuTienPanel extends javax.swing.JPanel {

    private ThuTienPanelController controller = null;
    private HoKhauBean hoKhauBean;
    private JFrame parentJFrame;
    /**
     * Creates new form ThuTienPanel
     */
    public ThuTienPanel(JFrame parentJFrame) {
        initComponents();
        this.hoKhauBean = new HoKhauBean();
        this.parentJFrame = parentJFrame;
        controller = new ThuTienPanelController(hoKhauBean, searchJtf, tableJpn);
        controller.setDataJtf(maHoKhauJtf, tenChuHoJtf, maKhuVucJtf, diaChiJta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The conteThuTienPanelControllernt of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        maHoKhauJtf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tableJpn = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tenChuHoJtf = new javax.swing.JTextField();
        maKhuVucJtf = new javax.swing.JTextField();
        searchJtf = new javax.swing.JTextField();
        thuTienBtn = new javax.swing.JButton();
        lichSuBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        diaChiJta = new javax.swing.JTextArea();
        quanLyKhoanThuBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Nhập mã hộ khẩu");

        maHoKhauJtf.setEditable(false);
        maHoKhauJtf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        maHoKhauJtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maHoKhauJtfActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Chọn hộ khẩu");

        tableJpn.setBackground(new java.awt.Color(255, 255, 255));
        tableJpn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout tableJpnLayout = new javax.swing.GroupLayout(tableJpn);
        tableJpn.setLayout(tableJpnLayout);
        tableJpnLayout.setHorizontalGroup(
            tableJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 261, Short.MAX_VALUE)
        );
        tableJpnLayout.setVerticalGroup(
            tableJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Mã hộ khẩu");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Tên chủ hộ");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Mã khu vực");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Địa chỉ");

        tenChuHoJtf.setEditable(false);
        tenChuHoJtf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tenChuHoJtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenChuHoJtfActionPerformed(evt);
            }
        });

        maKhuVucJtf.setEditable(false);
        maKhuVucJtf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        maKhuVucJtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maKhuVucJtfActionPerformed(evt);
            }
        });

        searchJtf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        searchJtf.setHighlighter(null);
        searchJtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchJtfActionPerformed(evt);
            }
        });

        thuTienBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        thuTienBtn.setText("Thu tiền");
        thuTienBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thuTienBtnActionPerformed(evt);
            }
        });

        lichSuBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lichSuBtn.setText("Lịch sử");
        lichSuBtn.setToolTipText("");
        lichSuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lichSuBtnActionPerformed(evt);
            }
        });

        diaChiJta.setEditable(false);
        diaChiJta.setBackground(new java.awt.Color(240, 240, 240));
        diaChiJta.setColumns(20);
        diaChiJta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        diaChiJta.setRows(5);
        jScrollPane1.setViewportView(diaChiJta);

        quanLyKhoanThuBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        quanLyKhoanThuBtn.setText("Quản lý khoản thu");
        quanLyKhoanThuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLyKhoanThuBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)))
                        .addComponent(searchJtf, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(quanLyKhoanThuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tableJpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(maKhuVucJtf))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(maHoKhauJtf))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tenChuHoJtf))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(thuTienBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lichSuBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchJtf, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(quanLyKhoanThuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 26, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(maHoKhauJtf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(thuTienBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lichSuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(tenChuHoJtf))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(maKhuVucJtf))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tableJpn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(48, 48, 48))))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void maHoKhauJtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maHoKhauJtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maHoKhauJtfActionPerformed

    private void tenChuHoJtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenChuHoJtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenChuHoJtfActionPerformed

    private void maKhuVucJtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maKhuVucJtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maKhuVucJtfActionPerformed

    private void searchJtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchJtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchJtfActionPerformed

    
    private void lichSuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lichSuBtnActionPerformed
        LichSuJFrame lichSuJFrame = new LichSuJFrame(this.parentJFrame);
        lichSuJFrame.setLocationRelativeTo(null);
        lichSuJFrame.setResizable(false);
        lichSuJFrame.setVisible(true);
    }//GEN-LAST:event_lichSuBtnActionPerformed

    private void quanLyKhoanThuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanLyKhoanThuBtnActionPerformed
        QuanLyKhoanThuJFrame quanLyKhoanThuJFrame = new QuanLyKhoanThuJFrame(this.controller, this.parentJFrame);
        quanLyKhoanThuJFrame.setLocationRelativeTo(null);
        quanLyKhoanThuJFrame.setResizable(false);
        quanLyKhoanThuJFrame.setVisible(true);
    }//GEN-LAST:event_quanLyKhoanThuBtnActionPerformed

    private void thuTienBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thuTienBtnActionPerformed
        ThuTienJFrame thuTienJFrame = new ThuTienJFrame(this.controller, this.parentJFrame);
        thuTienJFrame.setLocationRelativeTo(null);
        thuTienJFrame.setResizable(true);
        thuTienJFrame.setVisible(true);
    }//GEN-LAST:event_thuTienBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea diaChiJta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lichSuBtn;
    private javax.swing.JTextField maHoKhauJtf;
    private javax.swing.JTextField maKhuVucJtf;
    private javax.swing.JButton quanLyKhoanThuBtn;
    private javax.swing.JTextField searchJtf;
    private javax.swing.JPanel tableJpn;
    private javax.swing.JTextField tenChuHoJtf;
    private javax.swing.JButton thuTienBtn;
    // End of variables declaration//GEN-END:variables
}
